Repository UNN-ITMM-Software/devtools-course-practice, pull requests merged in 2021-04, with the labels that each got.

#144 Гусарова Д.А. 381806-2 ЛР №1
  modules/complex-number/test/test_gusarova_daria_complex_number.cpp
Labels: lab1

#129 Гурылев Н.С. 381806-3 ЛР1
  modules/complex-number/test/test_gurylev_nikita_complex_number.cpp
Labels: lab1

#142 Макаров А.А. 381806-1. ЛР1
  modules/complex-number/test/test_makarov_alexander_complex_number.cpp
Labels: lab1

#152 Алибеков М.Р. 381806-1 ЛР №1
  modules/complex-number/test/test_alibekov_murad_complex_number.cpp
Labels: lab1

#149 Галиндо Буитраго Х.С. 381806-4. ЛР1
  lab-guide/topics.md
  modules/complex-number/test/test_Galindo_Buitrago_Julio_Cesar_complex_number.cpp
Labels: lab1

#150 Цветков М.С. 381803-2. ЛР1.
  modules/complex-number/test/test_tsvetkov_maksim_complex_number.cpp
Labels: lab1

#159 Гогов В.И. 381806-1. ЛР2.
  modules/dheap/CMakeLists.txt
  modules/dheap/include/dheap.h
  modules/dheap/src/CMakeLists.txt
  modules/dheap/src/dheap.cpp
  modules/dheap/test/CMakeLists.txt
  modules/dheap/test/test_dheap.cpp
  modules/dheap/test/test_main.cpp
Labels: lab2

#157 Волкова А.Д. 381806-2. ЛР2.
  modules/Kruskal_algorithm/CMakeLists.txt
  modules/Kruskal_algorithm/README.md
  modules/Kruskal_algorithm/include/Kruskal_algorithm.h
  modules/Kruskal_algorithm/src/CMakeLists.txt
  modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
  modules/Kruskal_algorithm/test/CMakeLists.txt
  modules/Kruskal_algorithm/test/test_Kruskal_algorithm.cpp
  modules/Kruskal_algorithm/test/test_main.cpp
Labels: lab2

#158 Белик Ю.А. 381806-1. ЛР2.
  modules/triangle-point/CMakeLists.txt
  modules/triangle-point/README.md
  modules/triangle-point/include/TrianglePoint.h
  modules/triangle-point/src/CMakeLists.txt
  modules/triangle-point/src/TrianglePoint.cpp
  modules/triangle-point/test/CMakeLists.txt
  modules/triangle-point/test/test_main.cpp
  modules/triangle-point/test/test_triangle_point.cpp
Labels: lab2

#163 Власов М. С. 381806-1 ЛР №2
  modules/vector/CMakeLists.txt
  modules/vector/include/vector.h
  modules/vector/src/CMakeLists.txt
  modules/vector/src/vector.cpp
  modules/vector/test/CMakeLists.txt
  modules/vector/test/test_main.cpp
  modules/vector/test/test_vector.cpp
Labels: lab2

#162 Шагов Максим. 381806-1. ЛР2.
  modules/30_rule/CMakeLists.txt
  modules/30_rule/README.md
  modules/30_rule/include/30_rule.h
  modules/30_rule/src/30_rule.cpp
  modules/30_rule/src/CMakeLists.txt
  modules/30_rule/test/CMakeLists.txt
  modules/30_rule/test/test_30_rule.cpp
  modules/30_rule/test/test_main.cpp
Labels: lab2

#166 Тактаев А.А. 381806-1 ЛР2
  modules/qsort/CMakeLists.txt
  modules/qsort/include/qsort.h
  modules/qsort/src/CMakeLists.txt
  modules/qsort/src/qsort.cpp
  modules/qsort/test/CMakeLists.txt
  modules/qsort/test/test_main.cpp
  modules/qsort/test/test_qsort.cpp
Labels: lab2

#168 Зореев М.В. 381806-1 ЛР2
  modules/radix_sort/CMakeLists.txt
  modules/radix_sort/include/radix_sort.h
  modules/radix_sort/test/CMakeLists.txt
  modules/radix_sort/test/test_main.cpp
  modules/radix_sort/test/test_radix_sort.cpp
Labels: lab2

#173 Воденеев М.В. 381803-2 ЛР2
  modules/hanoi_tower/CMakeLists.txt
  modules/hanoi_tower/include/hanoi_tower.h
  modules/hanoi_tower/src/CMakeLists.txt
  modules/hanoi_tower/src/hanoi_tower.cpp
  modules/hanoi_tower/test/CMakeLists.txt
  modules/hanoi_tower/test/test_main.cpp
  modules/hanoi_tower/test/test_vodeneev_mikhail_hanoi_tower.cpp
Labels: lab2

#170 Курникова А.А. 381803-2 ЛР2
  modules/search-graph-diameter/CMakeLists.txt
  modules/search-graph-diameter/include/search-graph-diameter.h
  modules/search-graph-diameter/src/CMakeLists.txt
  modules/search-graph-diameter/src/search-graph-diameter.cpp
  modules/search-graph-diameter/test/CMakeLists.txt
  modules/search-graph-diameter/test/test-main.cpp
  modules/search-graph-diameter/test/test-search-graph-diameter.cpp
Labels: lab2

#176 Колесников Глеб 381803-2 ЛР2
  modules/bulls-n-cows/CMakeLists.txt
  modules/bulls-n-cows/include/BullsAndCows.h
  modules/bulls-n-cows/src/BullsAndCows.cpp
  modules/bulls-n-cows/src/CMakeLists.txt
  modules/bulls-n-cows/test/CMakeLists.txt
  modules/bulls-n-cows/test/test_bulls_and_cows.cpp
  modules/bulls-n-cows/test/test_main.cpp
Labels: lab2

#164 Черных Д.А. 381803-2 ЛР_2
  modules/prime_numbers/CMakeLists.txt
  modules/prime_numbers/include/prime_numbers.h
  modules/prime_numbers/src/CMakeLists.txt
  modules/prime_numbers/src/prime_numbers.cpp
  modules/prime_numbers/test/CMakeLists.txt
  modules/prime_numbers/test/test_main.cpp
  modules/prime_numbers/test/test_prime_numbers.cpp
Labels: lab2

#178 Мишин Илья 381803-2 ЛР2
  modules/euler_func/CMakeLists.txt
  modules/euler_func/README.md
  modules/euler_func/include/Euler.h
  modules/euler_func/src/CMakeLists.txt
  modules/euler_func/src/Euler.cpp
  modules/euler_func/test/CMakeLists.txt
  modules/euler_func/test/test_Euler.cpp
  modules/euler_func/test/test_main.cpp
Labels: lab2

#169 Кудрявцев А. С. 381803-2 ЛР2
  modules/Ceasar_cipher/CMakeLists.txt
  modules/Ceasar_cipher/include/cipher.h
  modules/Ceasar_cipher/src/CMakeLists.txt
  modules/Ceasar_cipher/src/cipher.cpp
  modules/Ceasar_cipher/test/CMakeLists.txt
  modules/Ceasar_cipher/test/test_cipher.cpp
  modules/Ceasar_cipher/test/test_main.cpp
Labels: lab2

#188 Рустамов Азер. 381806-1. ЛР2.
  modules/dijkstras-algorithm/CMakeLists.txt
  modules/dijkstras-algorithm/include/dijkstras_algorithm.h
  modules/dijkstras-algorithm/src/CMakeLists.txt
  modules/dijkstras-algorithm/src/dijkstras_algorithm.cpp
  modules/dijkstras-algorithm/test/CMakeLists.txt
  modules/dijkstras-algorithm/test/test_dijkstras_algorithm.cpp
  modules/dijkstras-algorithm/test/test_main.cpp
Labels: lab2

#196 Пестреев Д. С. 381806-2. ЛР2.
  modules/connectivity_components/CMakeLists.txt
  modules/connectivity_components/include/connectivity_components.h
  modules/connectivity_components/src/CMakeLists.txt
  modules/connectivity_components/src/connectivity_components.cpp
  modules/connectivity_components/test/CMakeLists.txt
  modules/connectivity_components/test/test_connectivity_components.cpp
  modules/connectivity_components/test/test_main.cpp
Labels: lab2

#194 Напылов Е. И. 381806-2. ЛР2.
  modules/interpolation-search/CMakeLists.txt
  modules/interpolation-search/include/interpolation_search.h
  modules/interpolation-search/src/CMakeLists.txt
  modules/interpolation-search/src/interpolation_search.cpp
  modules/interpolation-search/test/CMakeLists.txt
  modules/interpolation-search/test/test_interpolation_search.cpp
  modules/interpolation-search/test/test_main.cpp
Labels: lab2

#175 Молоткова Светлана. 381806-1. ЛР2.
  modules/quadratic_equation/CMakeLists.txt
  modules/quadratic_equation/README.md
  modules/quadratic_equation/include/QuadraticEquation.h
  modules/quadratic_equation/src/CMakeLists.txt
  modules/quadratic_equation/src/QuadraticEquation.cpp
  modules/quadratic_equation/test/CMakeLists.txt
  modules/quadratic_equation/test/test_main.cpp
  modules/quadratic_equation/test/test_quadratic_equation.cpp
Labels: lab2

#193 Скрипаль А. Д. 381806-2. ЛР2
  modules/intersection_line/CMakeLists.txt
  modules/intersection_line/README.md
  modules/intersection_line/include/intersection_line.h
  modules/intersection_line/src/CMakeLists.txt
  modules/intersection_line/src/intersection_line.cpp
  modules/intersection_line/test/CMakeLists.txt
  modules/intersection_line/test/test_intersection_line.cpp
  modules/intersection_line/test/test_main.cpp
Labels: lab2

#229 Лукьянченко И.А. 381806-2. ЛР2
  modules/number_to_word/CMakeLists.txt
  modules/number_to_word/include/number_to_word.h
  modules/number_to_word/src/CMakeLists.txt
  modules/number_to_word/src/number_to_word.cpp
  modules/number_to_word/test/CMakeLists.txt
  modules/number_to_word/test/test_main.cpp
  modules/number_to_word/test/test_number_to_word.cpp
Labels: lab2

#217 Колесин А.С. 381806-2 ЛР2
  modules/complex-calc/CMakeLists.txt
  modules/complex-calc/include/complex_number.h
  modules/complex-calc/src/CMakeLists.txt
  modules/complex-calc/src/complex_number.cpp
  modules/complex-calc/test/CMakeLists.txt
  modules/complex-calc/test/test_main.cpp
Labels: lab2

#198 Прокофьева Елизавета. 381806-2. ЛР2.
  modules/statistic_values/CMakeLists.txt
  modules/statistic_values/include/statistic_values.h
  modules/statistic_values/src/CMakeLists.txt
  modules/statistic_values/src/statistic_values.cpp
  modules/statistic_values/test/CMakeLists.txt
  modules/statistic_values/test/test_main.cpp
  modules/statistic_values/test/test_statistic_values.cpp
Labels: lab2

#192 Логанов А. С. 381806-2. ЛР2.
  modules/intersectLineAndPlane/CMakeLists.txt
  modules/intersectLineAndPlane/README.md
  modules/intersectLineAndPlane/include/ilap.h
  modules/intersectLineAndPlane/src/CMakeLists.txt
  modules/intersectLineAndPlane/src/ilap.cpp
  modules/intersectLineAndPlane/test/CMakeLists.txt
  modules/intersectLineAndPlane/test/test_ilap.cpp
  modules/intersectLineAndPlane/test/test_main.cpp
Labels: lab2

#190 Безроднов Д.А. 381803-2 ЛР2
  modules/Vigener_cipher/CMakeLists.txt
  modules/Vigener_cipher/include/Vigener.h
  modules/Vigener_cipher/src/CMakeLists.txt
  modules/Vigener_cipher/src/Vigener.cpp
  modules/Vigener_cipher/test/CMakeLists.txt
  modules/Vigener_cipher/test/test_Vigener.cpp
  modules/Vigener_cipher/test/test_main.cpp
Labels: lab2

#237 Макаров А.А. 381806-1. ЛР2
  modules/binary_search/CMakeLists.txt
  modules/binary_search/include/binary_search.h
  modules/binary_search/test/CMakeLists.txt
  modules/binary_search/test/test_binary_search.cpp
  modules/binary_search/test/test_main.cpp
Labels: lab2

#228 Лебедев А. В. 381803-2. ЛР2
  modules/deposit_calc/CMakeLists.txt
  modules/deposit_calc/include/DepositCalc.h
  modules/deposit_calc/src/CMakeLists.txt
  modules/deposit_calc/src/DepositCalc.cpp
  modules/deposit_calc/test/CMakeLists.txt
  modules/deposit_calc/test/test_deposit_calc.cpp
  modules/deposit_calc/test/test_main.cpp
Labels: lab2

#215 Гогов В.И. 381806-1 ЛР3
  modules/30_rule/CMakeLists.txt
  modules/30_rule/CTestTests.txt
  modules/30_rule/application/CMakeLists.txt
  modules/30_rule/application/main.cpp
  modules/30_rule/include/cellular_state_application.h
  modules/30_rule/src/cellular_state_application.cpp
Labels: lab3

#203 Юрин С. И. 381806-2. ЛР2.
  modules/fraction-calc-by-using-gcd/CMakeLists.txt
  modules/fraction-calc-by-using-gcd/include/fraction.h
  modules/fraction-calc-by-using-gcd/src/CMakeLists.txt
  modules/fraction-calc-by-using-gcd/src/fraction.cpp
  modules/fraction-calc-by-using-gcd/test/CMakeLists.txt
  modules/fraction-calc-by-using-gcd/test/test_fraction-calc.cpp
  modules/fraction-calc-by-using-gcd/test/test_main.cpp
Labels: lab2

#236 Алибеков М.Р. 381806-1. ЛР2
  modules/polygon/CMakeLists.txt
  modules/polygon/include/polygon.h
  modules/polygon/src/CMakeLists.txt
  modules/polygon/src/polygon.cpp
  modules/polygon/test/CMakeLists.txt
  modules/polygon/test/test_main.cpp
  modules/polygon/test/test_polygon.cpp
Labels: lab2

#199 Груздева Диана. 381806-2. ЛР2.
  modules/stack/CMakeLists.txt
  modules/stack/README.md
  modules/stack/include/stack.h
  modules/stack/src/CMakeLists.txt
  modules/stack/src/stack.cpp
  modules/stack/test/CMakeLists.txt
  modules/stack/test/test_main.cpp
  modules/stack/test/test_stack.cpp
Labels: lab2

#225 Соловьев А.Ю. 381806-1. ЛР2
  modules/batcher-mergesort/CMakeLists.txt
  modules/batcher-mergesort/include/mergesort.h
  modules/batcher-mergesort/src/CMakeLists.txt
  modules/batcher-mergesort/src/mergesort.cpp
  modules/batcher-mergesort/test/CMakeLists.txt
  modules/batcher-mergesort/test/test_batchersort.cpp
  modules/batcher-mergesort/test/test_main.cpp
Labels: lab2

#246 Николаев Д.В. 381806-2. ЛР2
  modules/combination_generator/CMakeLists.txt
  modules/combination_generator/README.md
  modules/combination_generator/include/generator.h
  modules/combination_generator/src/CMakeLists.txt
  modules/combination_generator/src/generator.cpp
  modules/combination_generator/test/CMakeLists.txt
  modules/combination_generator/test/test.cpp
  modules/combination_generator/test/test_main.cpp
Labels: lab2

#256 Кириллов К.И. 381806-2. ЛР2
  modules/largest-subseq/CMakeLists.txt
  modules/largest-subseq/include/largest_subseq.h
  modules/largest-subseq/src/CMakeLists.txt
  modules/largest-subseq/src/largest_subseq.cpp
  modules/largest-subseq/test/CMakeLists.txt
  modules/largest-subseq/test/test_largest_subseq.cpp
  modules/largest-subseq/test/test_main.cpp
Labels: lab2

#223 Новожилова Е. М. 381806-2. ЛР2
  modules/modified_stack_minimums/CMakeLists.txt
  modules/modified_stack_minimums/README.md
  modules/modified_stack_minimums/include/modified_stack_minimums.h
  modules/modified_stack_minimums/src/CMakeLists.txt
  modules/modified_stack_minimums/src/modified_stack_minimums.cpp
  modules/modified_stack_minimums/test/CMakeLists.txt
  modules/modified_stack_minimums/test/test_main.cpp
  modules/modified_stack_minimums/test/test_modified_stack_minimums.cpp
Labels: lab2

#202 Щекотилова Юлия. 381806-3. ЛР2
  modules/mortgage/CMakeLists.txt
  modules/mortgage/include/mortgage.h
  modules/mortgage/src/CMakeLists.txt
  modules/mortgage/src/mortgage.cpp
  modules/mortgage/test/CMakeLists.txt
  modules/mortgage/test/test_main.cpp
  modules/mortgage/test/test_mortgage.cpp
Labels: lab2

#195 Кузнецов Н.С. 381806-3. ЛР2.
  modules/btree_out_search/CMakeLists.txt
  modules/btree_out_search/README.md
  modules/btree_out_search/include/btree.h
  modules/btree_out_search/src/CMakeLists.txt
  modules/btree_out_search/src/btree.cpp
  modules/btree_out_search/test/CMakeLists.txt
  modules/btree_out_search/test/test-btree_out_search.cpp
  modules/btree_out_search/test/test-main.cpp
Labels: lab2

#204 Чирков Р.Д. 381806-2. ЛР2.
  modules/reverse-polish-notation/CMakeLists.txt
  modules/reverse-polish-notation/include/rpn.h
  modules/reverse-polish-notation/src/CMakeLists.txt
  modules/reverse-polish-notation/src/rpn.cpp
  modules/reverse-polish-notation/test/CMakeLists.txt
  modules/reverse-polish-notation/test/test_main.cpp
  modules/reverse-polish-notation/test/test_rpn.cpp
Labels: lab2

#191 Александрычев А.С. 381806-2. ЛР2.
  modules/grosfeld-cipher/CMakeLists.txt
  modules/grosfeld-cipher/README.md
  modules/grosfeld-cipher/include/grosfeld_cipher.h
  modules/grosfeld-cipher/src/CMakeLists.txt
  modules/grosfeld-cipher/src/grosfeld_cipher.cpp
  modules/grosfeld-cipher/test/CMakeLists.txt
  modules/grosfeld-cipher/test/test_grosfeld_cipher.cpp
  modules/grosfeld-cipher/test/test_main.cpp
Labels: lab2

#242 Киселева А.С 381806-2. ЛР2.
  modules/matrix_operations/CMakeLists.txt
  modules/matrix_operations/include/matrix_operations.h
  modules/matrix_operations/src/CMakeLists.txt
  modules/matrix_operations/src/matrix_operations.cpp
  modules/matrix_operations/test/CMakeLists.txt
  modules/matrix_operations/test/test_main.cpp
  modules/matrix_operations/test/test_matrix_operations.cpp
Labels: lab2

#197 Ткачев А.И. 381806-2. ЛР2.
  modules/queue/CMakeLists.txt
  modules/queue/include/node.h
  modules/queue/include/queue.h
  modules/queue/src/CMakeLists.txt
  modules/queue/src/node.cpp
  modules/queue/src/queue.cpp
  modules/queue/test/CMakeLists.txt
  modules/queue/test/test_main.cpp
  modules/queue/test/test_node.cpp
  modules/queue/test/test_queue.cpp
Labels: lab2

#266 Перезалив! Ткачев А.И. 381806-2. ЛР2.
  modules/queue/test/test_queue.cpp
Labels: lab2

#241 Романюк С. С. 381806-2. ЛР2.
  modules/permutation_generator/CMakeLists.txt
  modules/permutation_generator/README.md
  modules/permutation_generator/include/permutation.h
  modules/permutation_generator/src/CMakeLists.txt
  modules/permutation_generator/src/permutation.cpp
  modules/permutation_generator/test/CMakeLists.txt
  modules/permutation_generator/test/test.cpp
  modules/permutation_generator/test/test_main.cpp
Labels: lab2

#232 Галкин В.А. 381806-2. ЛР2
  modules/pseudographics/CMakeLists.txt
  modules/pseudographics/include/Pseudographics.h
  modules/pseudographics/src/CMakeLists.txt
  modules/pseudographics/src/Pseudographics.cpp
  modules/pseudographics/test/CMakeLists.txt
  modules/pseudographics/test/test_galkin_vladislav_pseudographics.cpp
  modules/pseudographics/test/test_main.cpp
Labels: lab2

#171 Тюрмина А.Н. 381806-3 ЛР2
  modules/book_discount/CMakeLists.txt
  modules/book_discount/include/calculate_price.h
  modules/book_discount/src/CMakeLists.txt
  modules/book_discount/src/calculate_price.cpp
  modules/book_discount/test/CMakeLists.txt
  modules/book_discount/test/test_calc_price.cpp
Labels: lab2

#205 Панова О.Р. 381806-2. ЛР2.
  modules/3d_shapes_volume/CMakeLists.txt
  modules/3d_shapes_volume/include/3d_shapes_volume.h
  modules/3d_shapes_volume/src/3d_shapes_volume.cpp
  modules/3d_shapes_volume/src/CMakeLists.txt
  modules/3d_shapes_volume/test/CMakeLists.txt
  modules/3d_shapes_volume/test/test_3d_shapes_volume.cpp
  modules/3d_shapes_volume/test/test_main.cpp
Labels: lab2

#261 Чистов В.М. 381806-2. ЛР2.
  modules/long-arithmetic/CMakeLists.txt
  modules/long-arithmetic/include/long_arithmetic.h
  modules/long-arithmetic/src/CMakeLists.txt
  modules/long-arithmetic/src/long_arithmetic.cpp
  modules/long-arithmetic/test/CMakeLists.txt
  modules/long-arithmetic/test/test_long_arithmetic.cpp
  modules/long-arithmetic/test/test_main.cpp
Labels: lab2

#226 Лудина Д.А. 381806-3. ЛР2
  modules/algorithm-huffmana/CMakeLists.txt
  modules/algorithm-huffmana/include/algorithm_huffmana.h
  modules/algorithm-huffmana/src/CMakeLists.txt
  modules/algorithm-huffmana/src/algorithm_huffmana.cpp
  modules/algorithm-huffmana/test/CMakeLists.txt
  modules/algorithm-huffmana/test/test_algorithm_huffmana.cpp
  modules/algorithm-huffmana/test/test_main.cpp
Labels: lab2

#218 Кириченко Н.А. 381806-3 ЛР2
  modules/avl-tree/CMakeLists.txt
  modules/avl-tree/include/avl.h
  modules/avl-tree/src/CMakeLists.txt
  modules/avl-tree/src/avl.cpp
  modules/avl-tree/test/CMakeLists.txt
  modules/avl-tree/test/test_avl.cpp
  modules/avl-tree/test/test_main.cpp
Labels: lab2

#271 Ткачев Алексей. 381806-2. Исправление ЛР2.
  lab-guide/topics.md
  modules/queue/test/test_queue.cpp
Labels: lab2
