Repository UNN-ITMM-Software/devtools-course-practice, pull requests merged in 2021-06, with the labels that each got.

#301 Остапович Д.Е. 381806-4. ЛР2.
  3rdparty/cpplint.py
  modules/json-deserializer/CMakeLists.txt
  modules/json-deserializer/README.md
  modules/json-deserializer/include/json-deserializer.h
  modules/json-deserializer/src/CMakeLists.txt
  modules/json-deserializer/src/json-deserializer.cpp
  modules/json-deserializer/test/CMakeLists.txt
  modules/json-deserializer/test/test_json_deserializer.cpp
  modules/json-deserializer/test/test_lexer.cpp
  modules/json-deserializer/test/test_main.cpp
Labels: lab2

#359 Цветков М.С. 381803-2. ЛР3
  modules/string_calculator/CMakeLists.txt
  modules/string_calculator/CTestTests.txt
  modules/string_calculator/application/CMakeLists.txt
  modules/string_calculator/application/application.cpp
  modules/string_calculator/include/string_calculator.h
  modules/string_calculator/include/string_calculator_app.h
  modules/string_calculator/src/CMakeLists.txt
  modules/string_calculator/src/string_calculator.cpp
  modules/string_calculator/src/string_calculator_app.cpp
Labels: lab2, lab3

#367 Остапович Д.Е. 381806-4. ЛР3
  modules/json-deserializer/CMakeLists.txt
  modules/json-deserializer/CTestTests.txt
  modules/json-deserializer/application/CMakeLists.txt
  modules/json-deserializer/application/main.cpp
  modules/json-deserializer/include/application.h
  modules/json-deserializer/src/application.cpp
Labels: lab3

#302 Таширев И. Э. 381806-3. ЛР1
  modules/complex-number/test/test_Tashirev_Ivan_complex_number.cpp
Labels: lab1
