Repository UNN-ITMM-Software/devtools-course-practice, pull requests merged in 2024-03, with the labels that each got.

#23 lab1: Chuvashov Andrey
  modules/complex-number/test/test_Chuvashov_Andrey_complex_number.cpp
Labels: lab 1

#31 Борисов Савелий - Лабораторная работа #1
  modules/complex-number/test/test_Borisov_Saveliy_complex_number.cpp
Labels: lab 1

#29 lab1: Soloninko Andrey
  modules/complex-number/test/test_soloninko_andrey_complex_number.cpp
Labels: lab 1

#30 Виничук - Лабораторная работа #1
  modules/complex-number/test/test_Vinichuk_Timofey_complex_number.cpp
Labels: lab 1

#46 Makhinya Danil lab1
  modules/complex-number/test/test_makhinya_danil_complex_number.cpp
Labels: lab 1

#56 Ногин Денис лаба 1
  modules/complex-number/test/test_nogin_denis_complex_number.cpp
Labels: lab 1

#57 Makhinya Danil lab2
  modules/makhinya_d_dijkstra_algorithm/CMakeLists.txt
  modules/makhinya_d_dijkstra_algorithm/include/dijkstra_algoritm.h
  modules/makhinya_d_dijkstra_algorithm/src/CMakeLists.txt
  modules/makhinya_d_dijkstra_algorithm/src/dijkstra_algoritm.cpp
  modules/makhinya_d_dijkstra_algorithm/test/CMakeLists.txt
  modules/makhinya_d_dijkstra_algorithm/test/dijkstra_test.cpp
  modules/makhinya_d_dijkstra_algorithm/test/test_main.cpp
Labels: lab 2

#62 Kiselev Igor lab1
  modules/complex-number/test/test_Kiselev_Igor_complex_number.cpp
Labels: lab 1

#45 Lab 1
  modules/complex-number/test/test_kashin_stepan_complex_number.cpp
Labels: lab 1

#63 Иванченко Алексей - Лабораторная работа #1
  modules/complex-number/test/test_Ivanchenko_Aleksei_complex-number.cpp
Labels: lab 1

#65 Храмов Иван. Лабораторная работа №1
  modules/complex-number/test/test_Khramov_Ivan_complex_number.cpp
Labels: lab 1

#64 Savchuk anton lab1
  modules/complex-number/test/test_savchuk_anton_comlex_number.cpp
Labels: lab 1

#61 Реализовал 2 л.р.
  modules/yurin_a_prime_numbers_in_range/CMakeLists.txt
  modules/yurin_a_prime_numbers_in_range/include/getting_prime_numbers.h
  modules/yurin_a_prime_numbers_in_range/src/CMakeLists.txt
  modules/yurin_a_prime_numbers_in_range/src/getting_prime_numbers.cpp
  modules/yurin_a_prime_numbers_in_range/test/CMakeLists.txt
  modules/yurin_a_prime_numbers_in_range/test/test_main.cpp
  modules/yurin_a_prime_numbers_in_range/test/test_yurin_a_prime_numbers.cpp
Labels: lab 2

#73 Исправил ошибку в своей л.р. 2
  modules/yurin_a_prime_numbers_in_range/src/getting_prime_numbers.cpp
Labels: lab 2

#71 Smirnov Leonid - lab1
  modules/complex-number/test/test_smirnov_leonid_complex_number.cpp
Labels: lab 1

#74 Сафаров Нурлан. Лабораторная работа №1.
  modules/complex-number/test/test_safarov_nurlan_complex_number.cpp
Labels: lab 1

#22 lab1: Kuznetsov Artyom
  modules/complex-number/test/test_kuznetsov_artyom_FIIT3.cpp
Labels: lab 1

#25 lab2: Kuznetsov Artyom (AVL tree)
  modules/kuznetsov_a_lab2/CMakeLists.txt
  modules/kuznetsov_a_lab2/include/avltree.h
  modules/kuznetsov_a_lab2/src/CMakeLists.txt
  modules/kuznetsov_a_lab2/src/avltree.cpp
  modules/kuznetsov_a_lab2/test/CMakeLists.txt
  modules/kuznetsov_a_lab2/test/test_avltree.cpp
  modules/kuznetsov_a_lab2/test/test_main.cpp
Labels: lab 2

#76 Поздняков - Лабораторная работа #1
  modules/complex-number/test/test_Pozdnyakov_Vasya_complex_number.cpp
Labels: lab 1

#83 Иванов - Лабораторная работа 1
  modules/complex-number/test/test_ivanov_nikita_complex_number.cpp
Labels: lab 1, Ready for merge

#81 Куликов - Лабораторная работа #1
  modules/complex-number/test/test_kulikov_artem_complex_number.cpp
Labels: lab 1, Ready for merge

#94 Новая ветка для lab2
  lab-guide/topics.md
Labels: lab 2

#82 Скотин - Лабораторная работа #1
  lab-guide/topics.md
  modules/complex-number/test/test_skotin_alexander_complex_number.cpp
Labels: lab 1, Ready for merge

#66 lab2
  modules/kashin_s_lab2/CMakeLists.txt
  modules/kashin_s_lab2/include/GronsfeldCipher.h
  modules/kashin_s_lab2/src/CMakeLists.txt
  modules/kashin_s_lab2/src/GronsfeldCipher.cpp
  modules/kashin_s_lab2/test/CMakeLists.txt
  modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
  modules/kashin_s_lab2/test/test_main.cpp
Labels: lab 2

#86 Ногин Денис лаба 2
  modules/nogin_d_vigenere_cipher/CMakeLists.txt
  modules/nogin_d_vigenere_cipher/include/vigenere_cipher.h
  modules/nogin_d_vigenere_cipher/src/CMakeLists.txt
  modules/nogin_d_vigenere_cipher/src/vigenere_cipher.cpp
  modules/nogin_d_vigenere_cipher/test/CMakeLists.txt
  modules/nogin_d_vigenere_cipher/test/test_nogin_denis_vigenere_cipher.cpp
Labels: lab 2

#107 Васильев Иван лабораторная работа 1
  modules/complex-number/test/test_vasilev_ivan_complex_number.cpp
Labels: lab 1, Ready for merge

#101 lab1: Sokolova Daria
  modules/complex-number/test/test_sokolova_daria_complex_number.cpp
Labels: lab 1, Ready for merge

#104 [lab1] (Мухин Иван 3821Б1ПМоп3) added tests for complex numbers
  modules/complex-number/test/test_Mukhin_Ivan_complex_numbers.cpp
Labels: lab 1, Ready for merge

#112 Кириллов Максим. Лабораторная работа №1
  modules/complex-number/test/test_Kirillov_Maxim_complex_number.cpp
Labels: lab 1, Ready for merge

#118 lab3: Kuznetsov Artyom
  modules/nogin_d_vigenere_cipher/CMakeLists.txt
  modules/nogin_d_vigenere_cipher/CTestTests.txt
  modules/nogin_d_vigenere_cipher/application/CMakeLists.txt
  modules/nogin_d_vigenere_cipher/application/application.cpp
  modules/nogin_d_vigenere_cipher/include/vigenere_cipher.h
  modules/nogin_d_vigenere_cipher/include/vigenere_cipher_app.h
  modules/nogin_d_vigenere_cipher/src/vigenere_cipher.cpp
  modules/nogin_d_vigenere_cipher/src/vigenere_cipher_app.cpp
  modules/nogin_d_vigenere_cipher/test/test_nogin_denis_vigenere_cipher.cpp
Labels: lab 3, Ready for merge

#127 Kochetov-Nikolay-lab1
  modules/complex-number/test/test_kochetov_nikolay_complex_number.cpp
Labels: lab 1, Ready for merge

#126 Шмелев Иван - лабораторная работа №1
  modules/complex-number/test/test_Shmelev_Ivan_complex_number.cpp
Labels: lab 1, Ready for merge

#124 Тушенцова Карина - Лабораторная работа №1
  modules/complex-number/test/test_tushentsova_karina_complex_number.cpp
Labels: lab 1, Ready for merge

#122 Саратова Марина - Лабораторная работа №1
  modules/complex-number/test/test_Saratova_Marina_complex_number.cpp
Labels: lab 1, Ready for merge

#116 Коновалов - Лабораторная работа #1
  modules/complex-number/test/test_Konovalov_Igor_complex_numper.cpp
Labels: lab 1, Ready for merge

#106 Ванюшкин Дмитрий - Лабораторная работа №1
  modules/complex-number/test/test_vanushkin_dmitry_complex_number.cpp
Labels: lab 1, Ready for merge

#98 lab1: Morgachev Stepan
  modules/complex-number/test/test_morgachev_stepan_complex_number.cpp
Labels: lab 1, Ready for merge

#96 Соболь - Лабораторная работа №1
  modules/complex-number/test/test_Sobol_Liubov_complex_number.cpp
Labels: lab 1, Ready for merge

#93 Белан Вадим - лабораторная работа 1
  lab-guide/topics.md
  modules/complex-number/test/test_Belan_Vadim_complex_number.cpp
Labels: lab 1, Ready for merge

#89 Крисеев Михаил Лабораторная работа № 1
  modules/complex-number/test/test_Kriseev_Mikhail_complex_number.cpp
Labels: lab 1, Ready for merge

#130 Кокин Иван - Лабараторная №1
  modules/complex-number/test/test_Kokin_Ivan_complex_number.cpp
Labels: lab 1

#129 Troitskiy alexander lab1
  lab-guide/topics.md
  modules/complex-number/test/test_troitskiy_alexander_complex_number.cpp
Labels: lab 1, Ready for merge

#131 Карагодин Андрей - Лабораторная №1
  modules/complex-number/test/test_Karagodin_Andrey_complex_number.cpp
Labels: lab 1, Ready for merge

#134 Дерун Андрей - Лабораторная работа №1
  modules/complex-number/test/test_derun_andrey_complex_number.cpp
Labels: lab 1, Ready for merge

#108 Шемякина - Лабораторная работа #1
  lab-guide/topics.md
  modules/complex-number/test/test_Shemiakina_Alesia_complex_number.cpp
Labels: lab 1, Ready for merge

#136 Новостроев Иван. Лабораторная работа №1
  modules/complex-number/test/test_Novostroev_Ivan_complex-number.cpp
Labels: lab 1, Ready for merge

#139 Ekaterina Kistrimova lab1-done!
  modules/complex-number/test/test_kistrimova_ekaterina_complex_number.cpp
Labels: lab 1, Ready for merge

#140 Выбор тем
  lab-guide/topics.md
Labels: Ready for merge

#138 Added new tests for lab1
  modules/complex-number/test/test_kutarin_alexandr_complex_number.cpp
Labels: lab 1, Ready for merge

#137 Added 6 tests for lab1
  modules/complex-number/test/test_nikitin_kirill_complex_number.cpp
Labels: Ready for merge

#145 Platonova Maria lab1 well done
  modules/complex-number/test/test_platonova_maria_complex_number.cpp
Labels: lab 1, Ready for merge

#80 Kiselev igor task choosed
  lab-guide/topics.md
  modules/complex-number/test/test_Kiselev_Igor_complex_number.cpp
Labels: Ready for merge

#109 Салаев - Лабораторная работа #1
  modules/complex-number/test/test_salaev_vlad_complex_number.cpp
Labels: lab 1, Ready for merge

#111 Виденева-Лабораторная работа#1
  modules/complex-number/test/test_Videneva_Ekaterina_complex_number.cpp
Labels: lab 1, Ready for merge

#119 Шубин - Лабораторная работа #1
  modules/complex-number/test/test_shubin_mikhail_complex_number.cpp
Labels: lab 1, Ready for merge

#123 Касимцев Роман - 1 лабораторная работа
  modules/complex-number/test/test_Kasimtcev_Roman_complex_number.cpp
Labels: lab 1, Ready for merge

#103 Kozlov Mikhail lab1
  modules/complex-number/test/test_Kozlov_Mikhail_complex_number.cpp
Labels: lab 1, Ready for merge

#133 Винокуров - Лабораторная работа #1
  modules/complex-number/test/test_vinokurov_ivan_complex_number.cpp
Labels: lab 1, Ready for merge

#149 Лесников Никита. Лабораторная работа №1
  modules/complex-number/test/test_lesnikov_nikita_complex_number.cpp
Labels: lab 1
