Repository UNN-ITMM-Software/devtools-course-practice, pull requests merged in 2024-05, with the labels that each got.

#276 Кириллов Максим. Лабораторная работа №3
  modules/kulaev_e_increasing_the_contrast_lab2/CMakeLists.txt
  modules/kulaev_e_increasing_the_contrast_lab2/CTestTests.txt
  modules/kulaev_e_increasing_the_contrast_lab2/application/CMakeLists.txt
  modules/kulaev_e_increasing_the_contrast_lab2/application/increasing_contrast.cpp
  modules/kulaev_e_increasing_the_contrast_lab2/include/increasing_cont_app.h
  modules/kulaev_e_increasing_the_contrast_lab2/src/increasing_cont.cpp
  modules/kulaev_e_increasing_the_contrast_lab2/src/increasing_cont_app.cpp
Labels: lab 3, Ready for merge

#279 Киселёв Игорь. Лабораторная работа №3
  modules/kudinov_n_conways_game_of_life/CMakeLists.txt
  modules/kudinov_n_conways_game_of_life/CTestTests.txt
  modules/kudinov_n_conways_game_of_life/application/CMakeLists.txt
  modules/kudinov_n_conways_game_of_life/application/game_of_life_lab3.cpp
  modules/kudinov_n_conways_game_of_life/include/game_of_life_app.h
  modules/kudinov_n_conways_game_of_life/src/game_of_life_app.cpp
Labels: lab 3, Ready for merge

#320 Касимцев Роман Лабораторная работа 3
  modules/videneva_polynomial_calculator/CMakeLists.txt
  modules/videneva_polynomial_calculator/CTestTests.txt
  modules/videneva_polynomial_calculator/application/CMakeLists.txt
  modules/videneva_polynomial_calculator/application/application.cpp
  modules/videneva_polynomial_calculator/include/polynomial_calculator.h
  modules/videneva_polynomial_calculator/include/polynomial_calculator_application.h
  modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
  modules/videneva_polynomial_calculator/src/polynomial_calculator_application.cpp
  modules/videneva_polynomial_calculator/test/test_main.cpp
  modules/videneva_polynomial_calculator/test/test_polynomial_calculator.cpp
Labels: lab 3, Ready for merge

#323 Махиня Данил. Лабороторная №3
  modules/podyachikh_knight_moves_lab2/CMakeLists.txt
  modules/podyachikh_knight_moves_lab2/CTestTests.txt
  modules/podyachikh_knight_moves_lab2/application/CMakeLists.txt
  modules/podyachikh_knight_moves_lab2/application/app.cpp
  modules/podyachikh_knight_moves_lab2/include/chess_board.h
  modules/podyachikh_knight_moves_lab2/include/chess_board_app.h
  modules/podyachikh_knight_moves_lab2/src/chess_board_app.cpp
Labels: lab 3, Ready for merge

#327 Мартынов Александр Лабораторная работа №3
  modules/shubin_m_numeric_systems/CMakeLists.txt
  modules/shubin_m_numeric_systems/CTestTests.txt
  modules/shubin_m_numeric_systems/application/CMakeLists.txt
  modules/shubin_m_numeric_systems/application/application.cpp
  modules/shubin_m_numeric_systems/include/CustomNSNumber.hpp
  modules/shubin_m_numeric_systems/include/NumSysApplication.hpp
  modules/shubin_m_numeric_systems/src/CustomNSNumber.cpp
  modules/shubin_m_numeric_systems/src/NumSysApplication.cpp
Labels: lab 3, Ready for merge

#336 Боровков Сергей. Лабораторная работа №3 (coverage patch)
  modules/safarov_n_interpolation_search/CTestTests.txt
Labels: lab 3

#335 Карагодин Андрей - Лабораторная работа №3
  .gitignore
  modules/vinokurov_i_figure_surface/CMakeLists.txt
  modules/vinokurov_i_figure_surface/CTestTests.txt
  modules/vinokurov_i_figure_surface/application/CMakeLists.txt
  modules/vinokurov_i_figure_surface/application/figure_surface_application.cpp
  modules/vinokurov_i_figure_surface/include/figure_surface.h
  modules/vinokurov_i_figure_surface/include/figure_surface_app.h
  modules/vinokurov_i_figure_surface/src/figure_surface.cpp
  modules/vinokurov_i_figure_surface/src/figure_surface_app.cpp
  modules/vinokurov_i_figure_surface/test/test_figure_surface.cpp
  modules/vinokurov_i_figure_surface/test/test_main.cpp
Labels: lab 3, Ready for merge

#322 Шубин Михаил - Лабораторная работа 3
  modules/martynov_a_matrix_operations/CMakeLists.txt
  modules/martynov_a_matrix_operations/CTestTests.txt
  modules/martynov_a_matrix_operations/application/CMakeLists.txt
  modules/martynov_a_matrix_operations/application/main.cpp
  modules/martynov_a_matrix_operations/include/application.hpp
  modules/martynov_a_matrix_operations/include/tmatrix.h
  modules/martynov_a_matrix_operations/src/application.cpp
  modules/martynov_a_matrix_operations/test/test_tmatrix.cpp
Labels: lab 3, Ready for merge

#337 Ногин Денис лаба 3
  modules/kuznetsov_a_lab2/CMakeLists.txt
  modules/kuznetsov_a_lab2/CTestTests.txt
  modules/kuznetsov_a_lab2/application/CMakeLists.txt
  modules/kuznetsov_a_lab2/application/application.cpp
  modules/kuznetsov_a_lab2/include/avltree_app.h
  modules/kuznetsov_a_lab2/src/avltree_app.cpp
Labels: lab 3, Ready for merge

#339 Винокуров Иван - Лабораторная работа №3
  modules/karagodin_a_objvolumes/CMakeLists.txt
  modules/karagodin_a_objvolumes/CTestTests.txt
  modules/karagodin_a_objvolumes/application/CMakeLists.txt
  modules/karagodin_a_objvolumes/application/objvolumes.cpp
  modules/karagodin_a_objvolumes/include/objvolumes_app.h
  modules/karagodin_a_objvolumes/src/objvolumes_app.cpp
Labels: lab 3, Ready for merge

#348 Куликов Артём. Лабораторная работа №3.
  modules/ivanov_n_greatest_inc_subseq/CMakeLists.txt
  modules/ivanov_n_greatest_inc_subseq/CTestTests.txt
  modules/ivanov_n_greatest_inc_subseq/application/CMakeLists.txt
  modules/ivanov_n_greatest_inc_subseq/application/app.cpp
  modules/ivanov_n_greatest_inc_subseq/include/lis_app.h
  modules/ivanov_n_greatest_inc_subseq/src/lis_app.cpp
Labels: lab 3, Ready for merge

#345 Vasilev_i _lab3
  modules/kokin_i_station_sorting/CTestTests.txt
  modules/kokin_i_station_sorting/application/CMakeLists.txt
  modules/kokin_i_station_sorting/application/application.cpp
  modules/kokin_i_station_sorting/include/Console_app.h
  modules/kokin_i_station_sorting/include/sort_station.h
  modules/kokin_i_station_sorting/src/Console_app.cpp
  modules/kokin_i_station_sorting/src/sort_station.cpp
  modules/kokin_i_station_sorting/test/test_kokin_i_station_sorting.cpp
  modules/kokin_i_station_sorting/test/test_main.cpp
Labels: lab 3

#357 Тушенцова Карина. Лабораторная работа №3
  modules/Vasilev_i_lab2/CMakeLists.txt
  modules/Vasilev_i_lab2/CTestTests.txt
  modules/Vasilev_i_lab2/application/CMakeLists.txt
  modules/Vasilev_i_lab2/application/application.cpp
  modules/Vasilev_i_lab2/include/Combinations.h
  modules/Vasilev_i_lab2/include/Combinations_app.h
  modules/Vasilev_i_lab2/src/Combinations.cpp
  modules/Vasilev_i_lab2/src/Combinations_app.cpp
  modules/Vasilev_i_lab2/test/test_Combinations.cpp
Labels: lab 3, Ready for merge, delayed

#350 Podyachikh Mikhail. Lab 3
  modules/moiseev_n_deposit_calculator/CMakeLists.txt
  modules/moiseev_n_deposit_calculator/CTestTests.txt
  modules/moiseev_n_deposit_calculator/application/CMakeLists.txt
  modules/moiseev_n_deposit_calculator/application/main.cpp
  modules/moiseev_n_deposit_calculator/include/deposit_calculator_app.h
  modules/moiseev_n_deposit_calculator/src/deposit_calculator_app.cpp
Labels: lab 3, Ready for merge

#316 [lab3]: Мухин Иван 3821Б1ПМоп3 (coverage patch)
  modules/mukhin_i_vectors/CMakeLists.txt
  modules/mukhin_i_vectors/CTestTests.txt
  modules/mukhin_i_vectors/application/CMakeLists.txt
  modules/mukhin_i_vectors/application/vector_app.cpp
  modules/mukhin_i_vectors/include/vector_calculator.h
  modules/mukhin_i_vectors/include/vectors.h
  modules/mukhin_i_vectors/src/CMakeLists.txt
  modules/mukhin_i_vectors/src/vector_calculator.cpp
  modules/mukhin_i_vectors/test/CMakeLists.txt
  modules/mukhin_i_vectors/test/test_main.cpp
  modules/mukhin_i_vectors/test/test_vector_calculator.cpp
  modules/mukhin_i_vectors/test/test_vectors.cpp
Labels: lab 3

#353 Доставалов Семен - Лабораторная работа №3
  modules/kochetov_n_djarvis/CMakeLists.txt
  modules/kochetov_n_djarvis/CTestTests.txt
  modules/kochetov_n_djarvis/application/CMakeLists.txt
  modules/kochetov_n_djarvis/application/main_app.cpp
  modules/kochetov_n_djarvis/include/djarvis.h
  modules/kochetov_n_djarvis/include/djarvis_app.h
  modules/kochetov_n_djarvis/src/djarvis_app.cpp
Labels: lab 3

#328 Белан Вадим. Лабораторная работа №3.
  modules/savchuk_intersectio_lab2/CMakeLists.txt
  modules/savchuk_intersectio_lab2/CTestTests.txt
  modules/savchuk_intersectio_lab2/application/CMakeLists.txt
  modules/savchuk_intersectio_lab2/application/application.cpp
  modules/savchuk_intersectio_lab2/include/console_application.h
  modules/savchuk_intersectio_lab2/src/console_application.cpp
  modules/savchuk_intersectio_lab2/test/CMakeLists.txt
  modules/savchuk_intersectio_lab2/test/test_main.cpp
Labels: lab 3

#364 Жаткин Вячеслав - Лабораторная №3
  modules/kokin_i_station_sorting_2/CMakeLists.txt
  modules/kokin_i_station_sorting_2/CTestTests.txt
  modules/kokin_i_station_sorting_2/application/CMakeLists.txt
  modules/kokin_i_station_sorting_2/application/sort_station_application.cpp
  modules/kokin_i_station_sorting_2/include/sort_station.h
  modules/kokin_i_station_sorting_2/include/sort_station_app.h
  modules/kokin_i_station_sorting_2/src/CMakeLists.txt
  modules/kokin_i_station_sorting_2/src/sort_station.cpp
  modules/kokin_i_station_sorting_2/src/sort_station_app.cpp
  modules/kokin_i_station_sorting_2/test/CMakeLists.txt
  modules/kokin_i_station_sorting_2/test/test_kokin_i_station_sorting.cpp
  modules/kokin_i_station_sorting_2/test/test_main.cpp
Labels: lab 3, delayed

#349 Кистримова Екатерина. Лабораторная работа №3
  modules/sobol_l_bitset_lab2/CMakeLists.txt
  modules/sobol_l_bitset_lab2/CTestTests.txt
  modules/sobol_l_bitset_lab2/application/CMakeLists.txt
  modules/sobol_l_bitset_lab2/application/application.cpp
  modules/sobol_l_bitset_lab2/include/tbitfield_app.h
  modules/sobol_l_bitset_lab2/src/tbitfield_app.cpp
Labels: lab 3, Ready for merge

#352 Филатов Максим - Лабораторная работа 3
  modules/kutarin_a_lab2/CMakeLists.txt
  modules/kutarin_a_lab2/CTestTests.txt
  modules/kutarin_a_lab2/application/Application.cpp
  modules/kutarin_a_lab2/application/CMakeLists.txt
  modules/kutarin_a_lab2/include/deque.h
  modules/kutarin_a_lab2/include/dequeApp.h
  modules/kutarin_a_lab2/src/dequeApp.cpp
  modules/kutarin_a_lab2/test/test_kutarin_a_deque.cpp
Labels: lab 3, Ready for merge

#347 Кутарин Александр. Лабораторная работа №3
  modules/novostroev_i_linear_single_list/CMakeLists.txt
  modules/novostroev_i_linear_single_list/CTestTests.txt
  modules/novostroev_i_linear_single_list/application/Application.cpp
  modules/novostroev_i_linear_single_list/application/CMakeLists.txt
  modules/novostroev_i_linear_single_list/include/SinglLinkedList.h
  modules/novostroev_i_linear_single_list/include/linked_list.h
  modules/novostroev_i_linear_single_list/src/SinglLinkedList.cpp
  modules/novostroev_i_linear_single_list/test/test_linked_list.cpp
Labels: lab 3, Ready for merge

#367 Бахтияров Александр. Лабораторная работа 2.
  modules/bakhtiarov_a_priority_queue/CMakeLists.txt
  modules/bakhtiarov_a_priority_queue/include/priority_queue.h
  modules/bakhtiarov_a_priority_queue/src/CMakeLists.txt
  modules/bakhtiarov_a_priority_queue/src/priority_queue.cpp
  modules/bakhtiarov_a_priority_queue/test/CMakeLists.txt
  modules/bakhtiarov_a_priority_queue/test/test_main.cpp
  modules/bakhtiarov_a_priority_queue/test/test_priority_queue.cpp
Labels: lab 2, Ready for merge, delayed

#338 Соболь Любовь - Лабораторная работа №3
  modules/borisov_s_stack/CMakeLists.txt
  modules/borisov_s_stack/CTestTests.txt
  modules/borisov_s_stack/application/CMakeLists.txt
  modules/borisov_s_stack/application/application.cpp
  modules/borisov_s_stack/include/stack_app.h
  modules/borisov_s_stack/src/CMakeLists.txt
  modules/borisov_s_stack/src/stack_app.cpp
Labels: lab 3, Ready for merge

#354 Кочетов Николай. Лабораторная работа №3.
  modules/sokolova_d_queue/CMakeLists.txt
  modules/sokolova_d_queue/CTestTests.txt
  modules/sokolova_d_queue/application/CMakeLists.txt
  modules/sokolova_d_queue/application/application.cpp
  modules/sokolova_d_queue/include/queue.h
  modules/sokolova_d_queue/include/queue_app.h
  modules/sokolova_d_queue/src/queue.cpp
  modules/sokolova_d_queue/src/queue_app.cpp
Labels: lab 3, Ready for merge

#369 Бахтияров Александр. Задача 3.
  modules/kistrimova_e_mod_stack_lab2/CMakeLists.txt
  modules/kistrimova_e_mod_stack_lab2/CTestTests.txt
  modules/kistrimova_e_mod_stack_lab2/application/CMakeLists.txt
  modules/kistrimova_e_mod_stack_lab2/application/application.cpp
  modules/kistrimova_e_mod_stack_lab2/include/stackApp.h
  modules/kistrimova_e_mod_stack_lab2/src/CMakeLists.txt
  modules/kistrimova_e_mod_stack_lab2/src/stackApp.cpp
Labels: lab 3, Ready for merge, delayed

#278 Musaev ilgar - лабораторная работа №1
  modules/complex-number/test/test_Musaev_Ilgar_complex_number.cpp
Labels: lab 1, delayed

#346 Troitskiy a lab3
  modules/kozlov_m_graph_diam/CMakeLists.txt
  modules/kozlov_m_graph_diam/CTestTests.txt
  modules/kozlov_m_graph_diam/application/CMakeLists.txt
  modules/kozlov_m_graph_diam/application/application.cpp
  modules/kozlov_m_graph_diam/include/graph.h
  modules/kozlov_m_graph_diam/include/graph_app.h
  modules/kozlov_m_graph_diam/src/CMakeLists.txt
  modules/kozlov_m_graph_diam/src/graph.cpp
  modules/kozlov_m_graph_diam/src/graph_app.cpp
  modules/kozlov_m_graph_diam/test/CMakeLists.txt
  modules/kozlov_m_graph_diam/test/graph_test.cpp
  modules/kozlov_m_graph_diam/test/test_main.cpp
Labels: lab 3

#371 Новостроев Иван. Лабораторная работа №3
  modules/belan_bulls_cows_lab2/CMakeLists.txt
  modules/belan_bulls_cows_lab2/CTestTests.txt
  modules/belan_bulls_cows_lab2/application/CMakeLists.txt
  modules/belan_bulls_cows_lab2/application/application.cpp
  modules/belan_bulls_cows_lab2/include/bulls_cows_app.h
  modules/belan_bulls_cows_lab2/src/bulls_cows_app.cpp
Labels: lab 3, delayed

#315 Платонова Мария lab2
  modules/platonova-lab2/CMakeLists.txt
  modules/platonova-lab2/include/Triangle.h
  modules/platonova-lab2/src/CMakeLists.txt
  modules/platonova-lab2/src/Triangle.cpp
  modules/platonova-lab2/test/CMakeLists.txt
  modules/platonova-lab2/test/tests.cpp
Labels: lab 2, Ready for merge, delayed

#373 Федотов Кирилл. Лабораторная работа №2
  modules/fedotov_k_set/CMakeLists.txt
  modules/fedotov_k_set/include/set.h
  modules/fedotov_k_set/src/CMakeLists.txt
  modules/fedotov_k_set/src/set.cpp
  modules/fedotov_k_set/test/CMakeLists.txt
  modules/fedotov_k_set/test/test_main.cpp
  modules/fedotov_k_set/test/test_set.cpp
Labels: lab 2, Ready for merge, delayed

#366 Савчук Антон. Лабораторная работа 3
  modules/bodrov_daniil_fibonacci_heap/CMakeList.txt
  modules/bodrov_daniil_fibonacci_heap/CMakeTests.txt
  modules/bodrov_daniil_fibonacci_heap/CTestTests.txt
  modules/bodrov_daniil_fibonacci_heap/application/CMakeList.txt
  modules/bodrov_daniil_fibonacci_heap/application/app.cpp
  modules/bodrov_daniil_fibonacci_heap/include/console.h
  modules/bodrov_daniil_fibonacci_heap/src/console.cpp
  modules/bodrov_daniil_fibonacci_heap/test/CMakeList.txt
Labels: lab 3, delayed

#374 Федотов Кирилл. Лабораторная работа №3
  modules/bakhtiarov_a_priority_queue/CMakeLists.txt
  modules/bakhtiarov_a_priority_queue/CTestTests.txt
  modules/bakhtiarov_a_priority_queue/application/CMakeLists.txt
  modules/bakhtiarov_a_priority_queue/application/application.cpp
  modules/bakhtiarov_a_priority_queue/include/priority_queue_app.h
  modules/bakhtiarov_a_priority_queue/src/priority_queue_app.cpp
Labels: lab 3, delayed

#378 add tests for lab1
  modules/complex-number/test/test_Safronov_Mikhail_complex_number.cpp
Labels: lab 1, delayed
