Repository UNN-ITMM-Software/devtools-course-practice, pull requests merged in 2024-04, with the labels that each got.

#85 Иванов Никита - Лабораторная работа 2
  modules/ivanov_n_greatest_inc_subseq/CMakeLists.txt
  modules/ivanov_n_greatest_inc_subseq/include/subseq.h
  modules/ivanov_n_greatest_inc_subseq/src/CMakeLists.txt
  modules/ivanov_n_greatest_inc_subseq/src/subseq.cpp
  modules/ivanov_n_greatest_inc_subseq/test/CMakeLists.txt
  modules/ivanov_n_greatest_inc_subseq/test/test_main.cpp
  modules/ivanov_n_greatest_inc_subseq/test/test_subseq.cpp
Labels: lab 2, Ready for merge

#148 Филатов Максим - лабораторная работа №1
  modules/complex-number/test/test_Filatov_Maxim_complex_number.cpp
Labels: lab 1

#153 Added new tests for lab1
  modules/complex-number/test/test_martynov_aleksandr_complex_number.cpp
Labels: lab 1

#165 Козлов Михаил. Лаба 2. Поиск диаметра графа
  modules/kozlov_m_graph_diam/CMakeLists.txt
  modules/kozlov_m_graph_diam/include/graph.h
  modules/kozlov_m_graph_diam/src/CMakeLists.txt
  modules/kozlov_m_graph_diam/src/graph.cpp
  modules/kozlov_m_graph_diam/test/CMakeLists.txt
  modules/kozlov_m_graph_diam/test/graph_test.cpp
  modules/kozlov_m_graph_diam/test/test_main.cpp
Labels: lab 2, Ready for merge

#173 Поздняков Василий. Лабораторная работа №2.
  modules/pozdnyakov_v_tower_of_hanoi/CMakeLists.txt
  modules/pozdnyakov_v_tower_of_hanoi/include/tower_of_hanoi.h
  modules/pozdnyakov_v_tower_of_hanoi/src/CMakeLists.txt
  modules/pozdnyakov_v_tower_of_hanoi/src/tower_of_hanoi.cpp
  modules/pozdnyakov_v_tower_of_hanoi/test/CMakeLists.txt
  modules/pozdnyakov_v_tower_of_hanoi/test/test_main.cpp
  modules/pozdnyakov_v_tower_of_hanoi/test/test_tower_of_hanoi.cpp
Labels: lab 2, Ready for merge

#161 Смирнова Дарья — Лабораторная работа №1
  modules/complex-number/test/test_Smirnova_Darya_complex_number.cpp
Labels: lab 1, Ready for merge

#175 Ходырев Федор. Лабораторная работа №2
  modules/khodyrev_f_point_hits_a_triangle/CMakeLists.txt
  modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
  modules/khodyrev_f_point_hits_a_triangle/src/CMakeLists.txt
  modules/khodyrev_f_point_hits_a_triangle/src/point_hits_a _triangle.cpp
  modules/khodyrev_f_point_hits_a_triangle/test/CMakeLists.txt
  modules/khodyrev_f_point_hits_a_triangle/test/test_khodyrev_f_point_hits_a_triangle.cpp
  modules/khodyrev_f_point_hits_a_triangle/test/test_main.cpp
Labels: lab 2, Ready for merge

#174 Моисеев Никита - Лабораторная работа 2
  modules/moiseev_n_deposit_calculator/CMakeLists.txt
  modules/moiseev_n_deposit_calculator/include/deposit_calculator.h
  modules/moiseev_n_deposit_calculator/src/CMakeLists.txt
  modules/moiseev_n_deposit_calculator/src/deposit_calculator.cpp
  modules/moiseev_n_deposit_calculator/test/CMakeLists.txt
  modules/moiseev_n_deposit_calculator/test/test_Moiseev_Nikita_moiseev_n_deposit_calculator.cpp
  modules/moiseev_n_deposit_calculator/test/test_main.cpp
Labels: lab 2, Ready for merge

#176 Солонинко Андрей. Лабораторная работа №2
  modules/soloninko_a_huffman_code/CMakeLists.txt
  modules/soloninko_a_huffman_code/include/huffman.h
  modules/soloninko_a_huffman_code/src/CMakeLists.txt
  modules/soloninko_a_huffman_code/src/huffman.cpp
  modules/soloninko_a_huffman_code/test/CMakeLists.txt
  modules/soloninko_a_huffman_code/test/huffman_test.cpp
Labels: lab 2, Ready for merge

#171 Храмов Иван. Лабораторная работа 2.
  modules/khramov_i_lab2/CMakeLists.txt
  modules/khramov_i_lab2/include/radix_sort.h
  modules/khramov_i_lab2/src/CMakeLists.txt
  modules/khramov_i_lab2/src/radix_sort.cpp
  modules/khramov_i_lab2/test/CMakeLists.txt
  modules/khramov_i_lab2/test/test_khramov_ivan_radix.cpp
  modules/khramov_i_lab2/test/test_main.cpp
Labels: lab 2, Ready for merge

#163 Боровков Сергей. Лабораторная работа №2.
  modules/borovkov_s_sort/CMakeLists.txt
  modules/borovkov_s_sort/include/insertion_sort.h
  modules/borovkov_s_sort/src/CMakeLists.txt
  modules/borovkov_s_sort/src/insertion_sort.cpp
  modules/borovkov_s_sort/test/CMakeLists.txt
  modules/borovkov_s_sort/test/test_insertion_sort.cpp
Labels: lab 2, Ready for merge

#117 Ванюшкин Дмитрий - Лабораторная работа №2
  modules/vanushkin_d_base64_converter/CMakeLists.txt
  modules/vanushkin_d_base64_converter/include/base64_converter.h
  modules/vanushkin_d_base64_converter/src/CMakeLists.txt
  modules/vanushkin_d_base64_converter/src/base64_converter.cpp
  modules/vanushkin_d_base64_converter/test/CMakeLists.txt
  modules/vanushkin_d_base64_converter/test/test_base64decoder.cpp
  modules/vanushkin_d_base64_converter/test/test_base64encoder.cpp
  modules/vanushkin_d_base64_converter/test/test_main.cpp
Labels: lab 2

#160 Кудинов Никита - Лабораторная работа №2
  modules/kudinov_n_conways_game_of_life/CMakeLists.txt
  modules/kudinov_n_conways_game_of_life/include/conways_game_of_life.h
  modules/kudinov_n_conways_game_of_life/src/CMakeLists.txt
  modules/kudinov_n_conways_game_of_life/src/conways_game_of_life.cpp
  modules/kudinov_n_conways_game_of_life/test/CMakeLists.txt
  modules/kudinov_n_conways_game_of_life/test/test_kudinov_n_conways_game_of_life.cpp
  modules/kudinov_n_conways_game_of_life/test/test_main.cpp
Labels: lab 2, Ready for merge

#191 Кулаев Евгений - Лабораторная работа #1
  modules/complex-number/test/test_Kulaev_Zhenya_complex_number.cpp
Labels: lab 1, Ready for merge

#186 Скотин Александр - Лабораторная работа 2
  modules/skotin_a_hashmap/CMakeLists.txt
  modules/skotin_a_hashmap/include/hashmap.h
  modules/skotin_a_hashmap/src/CMakeLists.txt
  modules/skotin_a_hashmap/src/hashmap.cpp
  modules/skotin_a_hashmap/test/CMakeLists.txt
  modules/skotin_a_hashmap/test/test_hashmap.cpp
  modules/skotin_a_hashmap/test/test_main.cpp
Labels: lab 2

#193 Кулаев Евгений - Лабораторная работа 2
  modules/kulaev_e_increasing_the_contrast_lab2/CMakeLists.txt
  modules/kulaev_e_increasing_the_contrast_lab2/include/increasing_cont.h
  modules/kulaev_e_increasing_the_contrast_lab2/src/CMakeLists.txt
  modules/kulaev_e_increasing_the_contrast_lab2/src/increasing_const.cpp
  modules/kulaev_e_increasing_the_contrast_lab2/test/CMakeLists.txt
  modules/kulaev_e_increasing_the_contrast_lab2/test/test_increas.cpp
  modules/kulaev_e_increasing_the_contrast_lab2/test/test_main.cpp
Labels: lab 2, Ready for merge

#215 Куликов Артём. Лабораторная работа №2.
  modules/kulikov_a_lab2/CMakeLists.txt
  modules/kulikov_a_lab2/include/lcs.h
  modules/kulikov_a_lab2/src/CMakeLists.txt
  modules/kulikov_a_lab2/src/lcs.cpp
  modules/kulikov_a_lab2/test/CMakeLists.txt
  modules/kulikov_a_lab2/test/test_lcs.cpp
  modules/kulikov_a_lab2/test/test_main.cpp
Labels: lab 2, Ready for merge

#188 Смирнов Л. Лабораторная Работа №2. Шифр Цезаря.
  modules/smirnov_l_caesar_cipher/CMakeLists.txt
  modules/smirnov_l_caesar_cipher/include/caesar_cipher.h
  modules/smirnov_l_caesar_cipher/src/CMakeLists.txt
  modules/smirnov_l_caesar_cipher/src/caesar_cipher.cpp
  modules/smirnov_l_caesar_cipher/test/CMakeLists.txt
  modules/smirnov_l_caesar_cipher/test/test_main.cpp
  modules/smirnov_l_caesar_cipher/test/test_smirnov_l_caesar_cipher.cpp
Labels: lab 2, Ready for merge

#198 Саратова Марина. Лабораторная работа №2
  modules/saratova_m_complex_number_calc/CMakeLists.txt
  modules/saratova_m_complex_number_calc/include/complex_number_calc.h
  modules/saratova_m_complex_number_calc/src/CMakeLists.txt
  modules/saratova_m_complex_number_calc/src/complex_number_calc.cpp
  modules/saratova_m_complex_number_calc/test/CMakeLists.txt
  modules/saratova_m_complex_number_calc/test/test_compex_number_calc.cpp
  modules/saratova_m_complex_number_calc/test/test_main.cpp
Labels: lab 2, Ready for merge

#201 Кириллов Максим. Лабораторная работа №2
  modules/kirillov_m_quadratic_solution/CMakeLists.txt
  modules/kirillov_m_quadratic_solution/include/quadratic_solution.h
  modules/kirillov_m_quadratic_solution/src/CMakeLists.txt
  modules/kirillov_m_quadratic_solution/src/quadratic_solution.cpp
  modules/kirillov_m_quadratic_solution/test/CMakeLists.txt
  modules/kirillov_m_quadratic_solution/test/test_main.cpp
  modules/kirillov_m_quadratic_solution/test/test_quadratic_solution.cpp
Labels: lab 2, Ready for merge

#199 Шмелев Иван. Лабораторная работа №2.
  modules/shmelev_i_graham_algorithm/CMakeLists.txt
  modules/shmelev_i_graham_algorithm/include/graham_algorithm.h
  modules/shmelev_i_graham_algorithm/src/CMakeLists.txt
  modules/shmelev_i_graham_algorithm/src/graham_algorithm.cpp
  modules/shmelev_i_graham_algorithm/test/CMakeLists.txt
  modules/shmelev_i_graham_algorithm/test/test_graham_algorithm.cpp
  modules/shmelev_i_graham_algorithm/test/test_main.cpp
Labels: lab 2, Ready for merge

#212 Коновалов Игорь - Лабораторная работа #2
  modules/konovalov_i_euler_f_lab2/CMakeLists.txt
  modules/konovalov_i_euler_f_lab2/include/konovalov_i_euler_f.h
  modules/konovalov_i_euler_f_lab2/src/CMakeLists.txt
  modules/konovalov_i_euler_f_lab2/src/konovalov_i_euler_f.cpp
  modules/konovalov_i_euler_f_lab2/test/CMakeLists.txt
  modules/konovalov_i_euler_f_lab2/test/test_konovalov_i_euler_f.cpp
  modules/konovalov_i_euler_f_lab2/test/test_main.cpp
Labels: lab 2, Ready for merge

#195 Крисеев Михаил - Лабораторная работа № 2
  modules/kriseev_m_vector_3d/CMakeLists.txt
  modules/kriseev_m_vector_3d/include/vector_3d.h
  modules/kriseev_m_vector_3d/src/CMakeLists.txt
  modules/kriseev_m_vector_3d/src/vector_3d.cpp
  modules/kriseev_m_vector_3d/test/CMakeLists.txt
  modules/kriseev_m_vector_3d/test/test_main.cpp
  modules/kriseev_m_vector_3d/test/vector_3d_tests.cpp
Labels: lab 2, Ready for merge

#200 Дерун Андрей - Лабораторная работа №2
  modules/derun_a_bisymmetric/CMakeLists.txt
  modules/derun_a_bisymmetric/include/bisymmetric.h
  modules/derun_a_bisymmetric/src/CMakeLists.txt
  modules/derun_a_bisymmetric/src/bisymmetric.cpp
  modules/derun_a_bisymmetric/test/CMakeLists.txt
  modules/derun_a_bisymmetric/test/test_derun_a_bisymmetric.cpp
  modules/derun_a_bisymmetric/test/test_main.cpp
Labels: lab 2, Ready for merge

#217 Жаткин Вячеслав Лабораторная работа №1
  modules/complex-number/test/test_zhatkin_vyacheslav_complex_number.cpp
Labels: lab 1, Ready for merge

#203 Доставалов Семен - Лабораторная работа №1
  modules/complex-number/test/test_dostavalov_semyon_complex_number.cpp
Labels: lab 1

#192 Чувашов Андрей - Лабораторная работа №2
  modules/chuvashov_a_ra_convertor/CMakeLists.txt
  modules/chuvashov_a_ra_convertor/include/ra_convertor.h
  modules/chuvashov_a_ra_convertor/src/CMakeLists.txt
  modules/chuvashov_a_ra_convertor/src/ra_convertor.cpp
  modules/chuvashov_a_ra_convertor/test/CMakeLists.txt
  modules/chuvashov_a_ra_convertor/test/test_main.cpp
  modules/chuvashov_a_ra_convertor/test/test_ra_convertor.cpp
Labels: lab 2

#230 Podyachikh Mikhail. Lab 1.
  modules/complex-number/test/test_podyachikh_mikhail_complex_number.cpp
Labels: lab 1

#219 Morgachev Stepan lab2
  modules/morgachev_s_batcher_merge/CMakeLists.txt
  modules/morgachev_s_batcher_merge/include/batcher_merge.h
  modules/morgachev_s_batcher_merge/src/CMakeLists.txt
  modules/morgachev_s_batcher_merge/src/batcher_merge.cpp
  modules/morgachev_s_batcher_merge/test/CMakeLists.txt
  modules/morgachev_s_batcher_merge/test/test_main.cpp
  modules/morgachev_s_batcher_merge/test/test_morgachev_s_batcher_merge.cpp
Labels: lab 2, Ready for merge

#227 Карагодин Андрей - Лабораторная работа №2.
  modules/karagodin_a_objvolumes/CMakeLists.txt
  modules/karagodin_a_objvolumes/include/objvolumes.h
  modules/karagodin_a_objvolumes/src/CMakeLists.txt
  modules/karagodin_a_objvolumes/src/objvolumes.cpp
  modules/karagodin_a_objvolumes/test/CMakeLists.txt
  modules/karagodin_a_objvolumes/test/test_main.cpp
  modules/karagodin_a_objvolumes/test/test_objvolumes.cpp
Labels: lab 2, Ready for merge

#232 Жаткин Вячеслав Лабораторная работа №2
  lab-guide/topics.md
  modules/zhatkin_v_levenshtein_distance/CMakeLists.txt
  modules/zhatkin_v_levenshtein_distance/include/levenshtein_distance.h
  modules/zhatkin_v_levenshtein_distance/src/CMakeLists.txt
  modules/zhatkin_v_levenshtein_distance/src/levenshtein_distance.cpp
  modules/zhatkin_v_levenshtein_distance/test/CMakeLists.txt
  modules/zhatkin_v_levenshtein_distance/test/test_main.cpp
  modules/zhatkin_v_levenshtein_distance/test/test_zhatkin_v_levenshtein_distance.cpp
Labels: lab 2, Ready for merge

#210 Тушенцова Карина - Лабораторная работа №2
  modules/tushentsova_k_permut_generator/CMakeLists.txt
  modules/tushentsova_k_permut_generator/include/permut_generator.h
  modules/tushentsova_k_permut_generator/src/CMakeLists.txt
  modules/tushentsova_k_permut_generator/src/permut_generator.cpp
  modules/tushentsova_k_permut_generator/test/CMakeLists.txt
  modules/tushentsova_k_permut_generator/test/test_main.cpp
  modules/tushentsova_k_permut_generator/test/test_permut_generator.cpp
Labels: lab 2, Ready for merge

#234 Филатов Максим - Лабораторная работа #2.
  modules/filatov_m_double_linked_list/CMakeLists.txt
  modules/filatov_m_double_linked_list/include/DoubleLinkedList.h
  modules/filatov_m_double_linked_list/src/CMakeLists.txt
  modules/filatov_m_double_linked_list/src/DoubleLinkedList.cpp
  modules/filatov_m_double_linked_list/test/CMakeLists.txt
  modules/filatov_m_double_linked_list/test/test_filatov_m_double_linked_list.cpp
  modules/filatov_m_double_linked_list/test/test_main.cpp
Labels: lab 2, Ready for merge

#168 Kiselev igor lab2
  modules/kiselev_i_billinear_interpolation/CMakeLists.txt
  modules/kiselev_i_billinear_interpolation/include/Billinear_interpolation.h
  modules/kiselev_i_billinear_interpolation/include/Color.h
  modules/kiselev_i_billinear_interpolation/src/Billinear_interpolation.cpp
  modules/kiselev_i_billinear_interpolation/src/CMakeLists.txt
  modules/kiselev_i_billinear_interpolation/src/Color.cpp
  modules/kiselev_i_billinear_interpolation/test/CMakeLists.txt
  modules/kiselev_i_billinear_interpolation/test/test_kiselev_i_billinear_interpolation.cpp
  modules/kiselev_i_billinear_interpolation/test/test_main.cpp
Labels: lab 2, Ready for merge

#238 Kochetov Nikolay lab2
  modules/kochetov_n_djarvis/CMakeLists.txt
  modules/kochetov_n_djarvis/include/djarvis.h
  modules/kochetov_n_djarvis/src/CMakeLists.txt
  modules/kochetov_n_djarvis/src/djarvis.cpp
  modules/kochetov_n_djarvis/test/CMakeLists.txt
  modules/kochetov_n_djarvis/test/test_djarvis.cpp
  modules/kochetov_n_djarvis/test/test_main.cpp
Labels: lab 2, Ready for merge

#225 Смирнова Дарья. Лабораторная работа №2
  modules/smirnova_d_fraction_calculator/CMakeLists.txt
  modules/smirnova_d_fraction_calculator/include/fraction_calculator.h
  modules/smirnova_d_fraction_calculator/src/CMakeLists.txt
  modules/smirnova_d_fraction_calculator/src/fraction_calculator.cpp
  modules/smirnova_d_fraction_calculator/test/CMakeLists.txt
  modules/smirnova_d_fraction_calculator/test/test_main.cpp
  modules/smirnova_d_fraction_calculator/test/test_smirnova_d_fraction_calculator.cpp
Labels: lab 2, Ready for merge

#187 Шубин Михаил - Лабораторная работа 2
  modules/shubin_m_numeric_systems/CMakeLists.txt
  modules/shubin_m_numeric_systems/include/CustomNSNumber.hpp
  modules/shubin_m_numeric_systems/src/CMakeLists.txt
  modules/shubin_m_numeric_systems/src/CustomNSNumber.cpp
  modules/shubin_m_numeric_systems/test/CMakeLists.txt
  modules/shubin_m_numeric_systems/test/test_main.cpp
  modules/shubin_m_numeric_systems/test/test_numeric_systems.cpp
Labels: lab 2, Ready for merge

#248 Бодров Даниил. Лабораторная работа 2. Fibonacci Heap
  modules/bodrov_daniil_fibonacci_heap/CMakeLists.txt
  modules/bodrov_daniil_fibonacci_heap/include/fibonacci_heap.h
  modules/bodrov_daniil_fibonacci_heap/src/CMakeLists.txt
  modules/bodrov_daniil_fibonacci_heap/src/fibonacci_heap.cpp
  modules/bodrov_daniil_fibonacci_heap/test/CMakeLists.txt
  modules/bodrov_daniil_fibonacci_heap/test/fibonacci_heap_test.cpp
  modules/bodrov_daniil_fibonacci_heap/test/test_main.cpp
Labels: lab 2, Ready for merge, delayed

#196 Соболь - Лабораторная работа №2
  modules/sobol_l_bitset_lab2/CMakeLists.txt
  modules/sobol_l_bitset_lab2/include/tbitfield.h
  modules/sobol_l_bitset_lab2/src/CMakeLists.txt
  modules/sobol_l_bitset_lab2/src/tbitfield.cpp
  modules/sobol_l_bitset_lab2/test/CMakeLists.txt
  modules/sobol_l_bitset_lab2/test/test_main.cpp
  modules/sobol_l_bitset_lab2/test/test_tbitfield.cpp
Labels: lab 2, Ready for merge

#233 Кутарин Александр. Лабораторная работа №2. Двухсторонняя очередь
  modules/kutarin_a_lab2/CMakeLists.txt
  modules/kutarin_a_lab2/include/deque.h
  modules/kutarin_a_lab2/src/CMakeLists.txt
  modules/kutarin_a_lab2/src/deque.cpp
  modules/kutarin_a_lab2/test/CMakeLists.txt
  modules/kutarin_a_lab2/test/test_kutarin_a_deque.cpp
  modules/kutarin_a_lab2/test/test_main.cpp
Labels: lab 2, Ready for merge

#211 Иванченко Алексей - Лабораторная работа #2
  modules/ivanchenko_a_metrics/CMakeLists.txt
  modules/ivanchenko_a_metrics/include/metrics.h
  modules/ivanchenko_a_metrics/src/CMakeLists.txt
  modules/ivanchenko_a_metrics/src/metrics.cpp
  modules/ivanchenko_a_metrics/test/CMakeLists.txt
  modules/ivanchenko_a_metrics/test/test_main.cpp
  modules/ivanchenko_a_metrics/test/test_metrics.cpp
Labels: lab 2

#235 Podyachikh Mikhail. Lab 2
  modules/podyachikh_knight_moves_lab2/CMakeLists.txt
  modules/podyachikh_knight_moves_lab2/include/chess_board.h
  modules/podyachikh_knight_moves_lab2/src/CMakeLists.txt
  modules/podyachikh_knight_moves_lab2/src/chess_board.cpp
  modules/podyachikh_knight_moves_lab2/test/CMakeLists.txt
  modules/podyachikh_knight_moves_lab2/test/test_Podyachikh_knight_dist.cpp
  modules/podyachikh_knight_moves_lab2/test/test_main.cpp
Labels: lab 2, Ready for merge

#244 Федотов - Лабораторная работа №1
  modules/complex-number/test/test_Fedotov_Kirill_complex_number.cpp
Labels: lab 1, Ready for merge

#91 Сафаров Нурлан. Лабораторная работа №2.
  modules/safarov_n_interpolation_search/CMakeLists.txt
  modules/safarov_n_interpolation_search/include/interpolation_search.h
  modules/safarov_n_interpolation_search/src/CMakeLists.txt
  modules/safarov_n_interpolation_search/src/interpolation_search.cpp
  modules/safarov_n_interpolation_search/test/CMakeLists.txt
  modules/safarov_n_interpolation_search/test/test_interpolation_search.cpp
  modules/safarov_n_interpolation_search/test/test_main.cpp
Labels: lab 2, Ready for merge

#224 Салаев Владислав - Лабораторная работа 2
  modules/salaev_vlad_json_decoder/CMakeLists.txt
  modules/salaev_vlad_json_decoder/include/json_decoder.h
  modules/salaev_vlad_json_decoder/src/CMakeLists.txt
  modules/salaev_vlad_json_decoder/src/json_decoder.cpp
  modules/salaev_vlad_json_decoder/test/CMakeLists.txt
  modules/salaev_vlad_json_decoder/test/test_json_decoder.cpp
  modules/salaev_vlad_json_decoder/test/test_main.cpp
Labels: lab 2, Ready for merge

#216 Виденева - Лабораторная работа #2.
  modules/videneva_polynomial_calculator/CMakeLists.txt
  modules/videneva_polynomial_calculator/include/polynomial_calculator.h
  modules/videneva_polynomial_calculator/src/CMakeLists.txt
  modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
  modules/videneva_polynomial_calculator/test/CMakeLists.txt
  modules/videneva_polynomial_calculator/test/test_main.cpp
  modules/videneva_polynomial_calculator/test/test_polynomial_calculator.cpp
Labels: lab 2, Ready for merge

#255 lab2: Мухин Иван 3821Б1ПМоп3. Численное интегрирование.
  .github/workflows/main.yml
  modules/mukhin_i_numerical_integration/CMakeLists.txt
  modules/mukhin_i_numerical_integration/include/integration_methods.h
  modules/mukhin_i_numerical_integration/src/CMakeLists.txt
  modules/mukhin_i_numerical_integration/src/integration_methods.cpp
  modules/mukhin_i_numerical_integration/test/CMakeLists.txt
  modules/mukhin_i_numerical_integration/test/test_integration.cpp
  modules/mukhin_i_numerical_integration/test/test_main.cpp
Labels: lab 2, delayed

#207 Виничук Тимофей. Лабораторная работа №2.
  modules/vinichuk_t_binary_search/CMakeLists.txt
  modules/vinichuk_t_binary_search/include/BinarySearch.h
  modules/vinichuk_t_binary_search/src/BinarySearch.cpp
  modules/vinichuk_t_binary_search/src/CMakeLists.txt
  modules/vinichuk_t_binary_search/test/CMakeLists.txt
  modules/vinichuk_t_binary_search/test/test_Vinichuk_Timofey_binary_search.cpp
  modules/vinichuk_t_binary_search/test/test_main.cpp
Labels: lab 2, Ready for merge

#271 Моисеев Никита. Лабораторная работа №3
  modules/chuvashov_a_ra_convertor/CMakeLists.txt
  modules/chuvashov_a_ra_convertor/CTestTests.txt
  modules/chuvashov_a_ra_convertor/application/CMakeLists.txt
  modules/chuvashov_a_ra_convertor/application/application.cpp
  modules/chuvashov_a_ra_convertor/include/ra_convertor_app.h
  modules/chuvashov_a_ra_convertor/src/ra_convertor_app.cpp
Labels: lab 3, Ready for merge

#265 Скотин Александр. Лабораторная работа №3
  modules/salaev_vlad_json_decoder/CMakeLists.txt
  modules/salaev_vlad_json_decoder/CTestTests.txt
  modules/salaev_vlad_json_decoder/application/CMakeLists.txt
  modules/salaev_vlad_json_decoder/application/json-decoder.cpp
  modules/salaev_vlad_json_decoder/include/json_app.h
  modules/salaev_vlad_json_decoder/include/json_decoder.h
  modules/salaev_vlad_json_decoder/src/json_app.cpp
Labels: lab 3, Ready for merge

#285 Morgachev Stepan lab3
  modules/zhatkin_v_levenshtein_distance/CMakeLists.txt
  modules/zhatkin_v_levenshtein_distance/CTestTests.txt
  modules/zhatkin_v_levenshtein_distance/application/CMakeLists.txt
  modules/zhatkin_v_levenshtein_distance/application/application.cpp
  modules/zhatkin_v_levenshtein_distance/include/levenshtein_distance_app.h
  modules/zhatkin_v_levenshtein_distance/src/levenshtein_distance_app.cpp
Labels: lab 3, Ready for merge

#264 Поздняков Василий. Лабораторная работа №3
  modules/khramov_i_lab2/CMakeLists.txt
  modules/khramov_i_lab2/CTestTests.txt
  modules/khramov_i_lab2/application/CMakeLists.txt
  modules/khramov_i_lab2/application/application.cpp
  modules/khramov_i_lab2/include/radix_sort.h
  modules/khramov_i_lab2/include/radix_sort_app.h
  modules/khramov_i_lab2/src/radix_sort_app.cpp
  modules/khramov_i_lab2/test/test_khramov_ivan_radix.cpp
Labels: lab 3, Ready for merge

#286 Ходырев Федор. Лабораторная работа №3
  modules/smirnov_l_caesar_cipher/CMakeLists.txt
  modules/smirnov_l_caesar_cipher/CTestTests.txt
  modules/smirnov_l_caesar_cipher/application/CMakeLists.txt
  modules/smirnov_l_caesar_cipher/application/application.cpp
  modules/smirnov_l_caesar_cipher/include/caesar_cipher.h
  modules/smirnov_l_caesar_cipher/include/caesar_cipher_app.h
  modules/smirnov_l_caesar_cipher/src/caesar_cipher.cpp
  modules/smirnov_l_caesar_cipher/src/caesar_cipher_app.cpp
  modules/smirnov_l_caesar_cipher/test/test_smirnov_l_caesar_cipher.cpp
Labels: lab 3, Ready for merge

#228 Vasilev_i_lab2
  modules/Vasilev_i_lab2/CMakeLists.txt
  modules/Vasilev_i_lab2/include/Combinations.h
  modules/Vasilev_i_lab2/src/CMakeLists.txt
  modules/Vasilev_i_lab2/src/Combinations.cpp
  modules/Vasilev_i_lab2/test/CMakeLists.txt
  modules/Vasilev_i_lab2/test/test_Combinations.cpp
  modules/Vasilev_i_lab2/test/test_main.cpp
Labels: lab 2, Ready for merge

#294 Шмелев Иван. Лабораторная работа №3
  modules/pozdnyakov_v_tower_of_hanoi/CMakeLists.txt
  modules/pozdnyakov_v_tower_of_hanoi/CTestTests.txt
  modules/pozdnyakov_v_tower_of_hanoi/application/CMakeLists.txt
  modules/pozdnyakov_v_tower_of_hanoi/application/application.cpp
  modules/pozdnyakov_v_tower_of_hanoi/include/tower_of_hanoi.h
  modules/pozdnyakov_v_tower_of_hanoi/include/tower_of_hanoi_app.h
  modules/pozdnyakov_v_tower_of_hanoi/src/tower_of_hanoi.cpp
  modules/pozdnyakov_v_tower_of_hanoi/src/tower_of_hanoi_app.cpp
  modules/pozdnyakov_v_tower_of_hanoi/test/test_tower_of_hanoi.cpp
Labels: lab 3, Ready for merge

#292 Саратова Марина. Лабораторная работа №3.
  modules/smirnova_d_fraction_calculator/CMakeLists.txt
  modules/smirnova_d_fraction_calculator/CTestTests.txt
  modules/smirnova_d_fraction_calculator/application/CMakeLists.txt
  modules/smirnova_d_fraction_calculator/application/application.cpp
  modules/smirnova_d_fraction_calculator/include/fraction_calculator.h
  modules/smirnova_d_fraction_calculator/include/fraction_calculator_app.h
  modules/smirnova_d_fraction_calculator/src/fraction_calculator.cpp
  modules/smirnova_d_fraction_calculator/src/fraction_calculator_app.cpp
  modules/smirnova_d_fraction_calculator/test/test_smirnova_d_fraction_calculator.cpp
Labels: lab 3, Ready for merge

#293 Чувашов Андрей. Лабораторная работа №3
  modules/morgachev_s_batcher_merge/CMakeLists.txt
  modules/morgachev_s_batcher_merge/CTestTests.txt
  modules/morgachev_s_batcher_merge/application/CMakeLists.txt
  modules/morgachev_s_batcher_merge/application/application.cpp
  modules/morgachev_s_batcher_merge/include/batcher_merge_app.h
  modules/morgachev_s_batcher_merge/src/batcher_merge.cpp
  modules/morgachev_s_batcher_merge/src/batcher_merge_app.cpp
Labels: lab 3, Ready for merge

#291 Виденева Екатерина-Лабораторная работа#3
  modules/konovalov_i_euler_f_lab2/CMakeLists.txt
  modules/konovalov_i_euler_f_lab2/CTestTests.txt
  modules/konovalov_i_euler_f_lab2/application/CMakeLists.txt
  modules/konovalov_i_euler_f_lab2/application/euler_f.cpp
  modules/konovalov_i_euler_f_lab2/include/konovalov_i_euler_f.h
  modules/konovalov_i_euler_f_lab2/include/konovalov_i_euler_f_app.h
  modules/konovalov_i_euler_f_lab2/src/konovalov_i_euler_f_app.cpp
Labels: lab 3, Ready for merge

#239 Troitskiy a lab2
  modules/troitskiy_a_lab2/CMakeLists.txt
  modules/troitskiy_a_lab2/include/lab2.h
  modules/troitskiy_a_lab2/src/CMakeLists.txt
  modules/troitskiy_a_lab2/src/lab2.cpp
  modules/troitskiy_a_lab2/test/CMakeLists.txt
  modules/troitskiy_a_lab2/test/lab.cpp
  modules/troitskiy_a_lab2/test/lab2.cpp
Labels: lab 2, Ready for merge

#260 Соколова Дарья. Лабораторная работа №2. Очередь.
  modules/sokolova_d_queue/CMakeLists.txt
  modules/sokolova_d_queue/include/queue.h
  modules/sokolova_d_queue/src/CMakeLists.txt
  modules/sokolova_d_queue/src/queue.cpp
  modules/sokolova_d_queue/test/CMakeLists.txt
  modules/sokolova_d_queue/test/test_main.cpp
  modules/sokolova_d_queue/test/test_queue.cpp
Labels: lab 2, Ready for merge, delayed

#275 Кудинов Никита. Лабораторная работа №3
  modules/dostavalov_s_knuth_morris_pratt/CMakeLists.txt
  modules/dostavalov_s_knuth_morris_pratt/CTestTests.txt
  modules/dostavalov_s_knuth_morris_pratt/application/CMakeLists.txt
  modules/dostavalov_s_knuth_morris_pratt/application/application.cpp
  modules/dostavalov_s_knuth_morris_pratt/include/KMP_app.h
  modules/dostavalov_s_knuth_morris_pratt/src/KMP_app.cpp
Labels: lab 3, Ready for merge

#301 Юрин Андрей. Лабораторная работа №3
  modules/kashin_s_lab2/CMakeLists.txt
  modules/kashin_s_lab2/CTestTests.txt
  modules/kashin_s_lab2/application/Application.cpp
  modules/kashin_s_lab2/application/CMakeLists.txt
  modules/kashin_s_lab2/include/GronsfeldCipher.h
  modules/kashin_s_lab2/include/GronsfeldCipherApp.h
  modules/kashin_s_lab2/src/GronsfeldCipher.cpp
  modules/kashin_s_lab2/src/GronsfeldCipherApp.cpp
Labels: lab 3, Ready for merge

#297 Смирнов Леонид. Лабораторная Работа №3.
  modules/kirillov_m_quadratic_solution/CMakeLists.txt
  modules/kirillov_m_quadratic_solution/CTestTests.txt
  modules/kirillov_m_quadratic_solution/application/CMakeLists.txt
  modules/kirillov_m_quadratic_solution/application/application.cpp
  modules/kirillov_m_quadratic_solution/include/quadratic_solution.h
  modules/kirillov_m_quadratic_solution/include/quadratic_solution_application.h
  modules/kirillov_m_quadratic_solution/src/quadratic_solution.cpp
  modules/kirillov_m_quadratic_solution/src/quadratic_solution_application.cpp
Labels: lab 3, Ready for merge

#252 Кокин Иван - lab2
  modules/kokin_i_station_sorting/CMakeLists.txt
  modules/kokin_i_station_sorting/include/sort_station.h
  modules/kokin_i_station_sorting/src/CMakeLists.txt
  modules/kokin_i_station_sorting/src/sort_station.cpp
  modules/kokin_i_station_sorting/test/CMakeLists.txt
  modules/kokin_i_station_sorting/test/test_kokin_i_station_sorting.cpp
  modules/kokin_i_station_sorting/test/test_main.cpp
Labels: lab 2, Ready for merge, delayed

#306 Крисеев Михаил. Лабораторная работа № 3
  modules/mukhin_i_numerical_integration/CMakeLists.txt
  modules/mukhin_i_numerical_integration/CTestTests.txt
  modules/mukhin_i_numerical_integration/application/CMakeLists.txt
  modules/mukhin_i_numerical_integration/application/main.cpp
  modules/mukhin_i_numerical_integration/include/numerical_integration_app.h
  modules/mukhin_i_numerical_integration/src/numerical_integration_app.cpp
Labels: lab 3, Ready for merge

#307 Lab 3
  modules/yurin_a_prime_numbers_in_range/CMakeLists.txt
  modules/yurin_a_prime_numbers_in_range/CTestTests.txt
  modules/yurin_a_prime_numbers_in_range/application/Application.cpp
  modules/yurin_a_prime_numbers_in_range/application/CMakeLists.txt
  modules/yurin_a_prime_numbers_in_range/include/console_handler.h
  modules/yurin_a_prime_numbers_in_range/include/getting_prime_numbers.h
  modules/yurin_a_prime_numbers_in_range/src/console_handler.cpp
  modules/yurin_a_prime_numbers_in_range/src/getting_prime_numbers.cpp
Labels: lab 3, Ready for merge

#247 Лесников Никита. Лабораторная работа 2. Числа произвольной длины
  modules/lesnikov_long_number/CMakeLists.txt
  modules/lesnikov_long_number/include/LongNumber.h
  modules/lesnikov_long_number/src/CMakeLists.txt
  modules/lesnikov_long_number/src/LongNumber.cpp
  modules/lesnikov_long_number/test/CMakeLists.txt
  modules/lesnikov_long_number/test/long-number_test.cpp
  modules/lesnikov_long_number/test/test_main.cpp
Labels: lab 2, Ready for merge, delayed

#269 Козлов Михаил - 3 лаба
  modules/troitskiy_a_lab2/CTestTests.txt
  modules/troitskiy_a_lab2/application/CMakeLists.txt
  modules/troitskiy_a_lab2/application/application.cpp
  modules/troitskiy_a_lab2/include/Heap_app.h
  modules/troitskiy_a_lab2/src/Heap_app.cpp
Labels: lab 3, Ready for merge

#303 Лесников Никита. Лабораторная работа №3
  modules/soloninko_a_huffman_code/CMakeLists.txt
  modules/soloninko_a_huffman_code/CTestTests.txt
  modules/soloninko_a_huffman_code/application/CMakeLists.txt
  modules/soloninko_a_huffman_code/application/application.cpp
  modules/soloninko_a_huffman_code/include/huffman.h
  modules/soloninko_a_huffman_code/include/huffman_app.h
  modules/soloninko_a_huffman_code/src/huffman.cpp
  modules/soloninko_a_huffman_code/src/huffman_app.cpp
  modules/soloninko_a_huffman_code/test/huffman_test.cpp
Labels: lab 3, Ready for merge

#312 Виничук Тимофей. Лабораторная работа №3.
  modules/complex-number/application/complex-number.cpp
  modules/khodyrev_f_point_hits_a_triangle/application/application.cpp
  modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle_app.h
  modules/khodyrev_f_point_hits_a_triangle/src/point_hits_a_triangle_app.cpp
  modules/kirillov_m_quadratic_solution/src/quadratic_solution.cpp
  modules/vanushkin_d_base64_converter/CMakeLists.txt
  modules/vanushkin_d_base64_converter/CTestTests.txt
  modules/vanushkin_d_base64_converter/application/CMakeLists.txt
  modules/vanushkin_d_base64_converter/application/application.cpp
  modules/vanushkin_d_base64_converter/include/base64_converter_app.h
  modules/vanushkin_d_base64_converter/src/base64_converter_app.cpp
Labels: lab 3

#313 Соколова Дарья. Лабораторная работа №3
  modules/kasimtcev_r_polskaya_zapis/CMakeLists.txt
  modules/kasimtcev_r_polskaya_zapis/CTestTests.txt
  modules/kasimtcev_r_polskaya_zapis/application/CMakeLists.txt
  modules/kasimtcev_r_polskaya_zapis/application/application.cpp
  modules/kasimtcev_r_polskaya_zapis/include/pol_not_app.h
  modules/kasimtcev_r_polskaya_zapis/src/pol_not_app.cpp
Labels: lab 3, Ready for merge

#314 Смирнова Дарья. Лабораторная работа №3.
  modules/saratova_m_complex_number_calc/CMakeLists.txt
  modules/saratova_m_complex_number_calc/CTestTests.txt
  modules/saratova_m_complex_number_calc/application/CMakeLists.txt
  modules/saratova_m_complex_number_calc/application/application.cpp
  modules/saratova_m_complex_number_calc/include/complex_number_calc.h
  modules/saratova_m_complex_number_calc/include/complex_number_calc_app.h
  modules/saratova_m_complex_number_calc/src/complex_number_calc.cpp
  modules/saratova_m_complex_number_calc/src/complex_number_calc_app.cpp
  modules/saratova_m_complex_number_calc/test/test_compex_number_calc.cpp
Labels: lab 3, Ready for merge

#236 Новостроев Иван. Лабораторная работа №2. Линейный односвязный список
  modules/novostroev_i_linear_single_list/CMakeLists.txt
  modules/novostroev_i_linear_single_list/include/linked_list.h
  modules/novostroev_i_linear_single_list/src/CMakeLists.txt
  modules/novostroev_i_linear_single_list/src/linked_list.cpp
  modules/novostroev_i_linear_single_list/test/CMakeLists.txt
  modules/novostroev_i_linear_single_list/test/test_linked_list.cpp
  modules/novostroev_i_linear_single_list/test/test_main.cpp
Labels: lab 2, Ready for merge

#305 Бодров Даниил. Лабораторная работа №3
  modules/kiselev_i_billinear_interpolation/CMakeLists.txt
  modules/kiselev_i_billinear_interpolation/CTestTests.txt
  modules/kiselev_i_billinear_interpolation/application/CMakeLists.txt
  modules/kiselev_i_billinear_interpolation/application/application.cpp
  modules/kiselev_i_billinear_interpolation/include/Billinear_interpolation.h
  modules/kiselev_i_billinear_interpolation/include/Billinear_interpolation_app.h
  modules/kiselev_i_billinear_interpolation/include/Color.h
  modules/kiselev_i_billinear_interpolation/src/Billinear_interpolation.cpp
  modules/kiselev_i_billinear_interpolation/src/Billinear_interpolation_app.cpp
  modules/kiselev_i_billinear_interpolation/src/Color.cpp
  modules/kiselev_i_billinear_interpolation/test/test_kiselev_i_billinear_interpolation.cpp
Labels: lab 3, Ready for merge

#268 Борисов Савелий - Лабораторная работа #3
  modules/vinichuk_t_binary_search/CMakeLists.txt
  modules/vinichuk_t_binary_search/CTestTests.txt
  modules/vinichuk_t_binary_search/application/CMakeLists.txt
  modules/vinichuk_t_binary_search/application/application.cpp
  modules/vinichuk_t_binary_search/include/BinarySearch.h
  modules/vinichuk_t_binary_search/include/BinarySearchApp.h
  modules/vinichuk_t_binary_search/src/BinarySearchApp.cpp
  modules/vinichuk_t_binary_search/test/test_Vinichuk_Timofey_binary_search.cpp
Labels: lab 3

#295 Сафаров Нурлан. Лабораторная работа №3.
  modules/makhinya_d_dijkstra_algorithm/CMakeLists.txt
  modules/makhinya_d_dijkstra_algorithm/CTestTests.txt
  modules/makhinya_d_dijkstra_algorithm/application/CMakeLists.txt
  modules/makhinya_d_dijkstra_algorithm/application/dijkstra_algoritm_app.cpp
  modules/makhinya_d_dijkstra_algorithm/include/dijkstra_algoritm_app.h
  modules/makhinya_d_dijkstra_algorithm/src/dijkstra_algoritm_app.cpp
  modules/makhinya_d_dijkstra_algorithm/test/dijkstra_test.cpp
Labels: lab 3, Ready for merge

#267 Дерун Андрей - Лабораторная работа №3
  modules/ivanchenko_a_metrics/CMakeLists.txt
  modules/ivanchenko_a_metrics/CTestTests.txt
  modules/ivanchenko_a_metrics/application/CMakeLists.txt
  modules/ivanchenko_a_metrics/application/metrics.cpp
  modules/ivanchenko_a_metrics/include/metrics_app.h
  modules/ivanchenko_a_metrics/src/metrics.cpp
  modules/ivanchenko_a_metrics/src/metrics_app.cpp
  modules/ivanchenko_a_metrics/test/test_metrics.cpp
Labels: lab 3, Ready for merge
